export function Nationality():string[]{

    let arr:string[]=['Afghan',
    'Albanian',
    'Algerian',
    'Argentine',
    'Argentinian',
    'Australian',
    'Austrian',
    'Bangladeshi',
    'Belgian',
    'Bolivian',
    'Batswana',
    'Brazilian',
    'Bulgarian',
    'Cambodian',
    'Cameroonian',
    'Canadian',
    'Chilean',
    'Chinese',
    'Colombian',
    'Costa Rican',
    'Croatian',
    'Cuban',
    'Czech',
    'Danish',
    'Dominican',
    'Ecuadorian',
    'Egyptian',
    'Salvadorian',
    'English',
    'Estonian',
    'Ethiopian',
    'Fijian',
    'Finnish',
    'French',
    'German',
    'Ghanaian',
    'Greek',
    'Guatemalan',
    'Haitian',
    'Honduran',
    'Hungarian',
    'Icelandic',
    'Indian',
    'Indonesian',
    'Iranian',
    'Iraqi',
    'Irish',
    'Israeli',
    'Italian',
    'Jamaican',
    'Japanese',
    'Jordanian',
    'Kenyan',
    'Kuwaiti',
    'Lao',
    'Latvian',
    'Lebanese',
    'Libyan',
    'Lithuanian',
    'Malagasy',
    'Malaysian',
    'Malian',
    'Maltese',
    'Mexican',
    'Mongolian',
    'Moroccan',
    'Mozambican',
    'Namibian',
    'Nepalese',
    'Dutch',
    'New Zealand',
    'Nicaraguan',
    'Nigerian',
    'Norwegian',
    'Pakistani',
    'Panamanian',
    'Paraguayan',
    'Peruvian',
    'Philippine',
    'Polish',
    'Portuguese',
    'Romanian',
    'Russian',
    'Saudi',
    'Scottish',
    'Senegalese',
    'Serbian',
    'Singaporean',
    'Slovak',
    'South African',
    'Korean',
    'Spanish',
    'Sri Lankan',
    'Sudanese',
    'Swedish',
    'Swiss',
    'Syrian',
    'Taiwanese',
    'Tajikistani',
    'Thai',
    'Tongan',
    'Tunisian',
    'Turkish',
    'Ukrainian',
    'Emirati',
    'British',
    'American **',
    'Uruguayan',
    'Venezuelan',
    'Vietnamese',
    'Welsh',
    'Zambian',
    'Zimbabwean'
    ]
    return arr;

}


export function titles():string[]{
    let title:string[]=['Mr.' ,'Mrs.']
    return title;
}
export function options():string[]{
    let option:string[]=['Yes' ,'No']
    return option;
}
export function gender():string[]{
    let gender:string[]=['Male' ,'Female','Unspecified']
    return gender;
}
export function maritalstatus():string[]{
    let status:string[]=['Single' ,'Married','Divorced']
    return status;
}
export function courses():string[]{
    let status:string[]=['10th(SSC)' ,
    '12th(HSC)',
    'B.Tech- Bachelor of Technology',
    'B.Arch- Bachelor of Architecture',
    'BCA- Bachelor of Computer Applications',
    'B.Sc.- Information Technology',
'B.Sc- Nursing','BPharma- Bachelor of Pharmacy',
'B.Sc- Interior Design',
'BDS- Bachelor of Dental Surgery',
'Animation, Graphics and Multimedia',
'B.Sc. – Nutrition & Dietetics',
'BPT- Bachelor of Physiotherapy',
'B.Sc- Applied Geology',
'BA/B.Sc. Liberal Arts',
'B.Sc.- Physics',
'B.Sc. Chemistry',
'B.Sc. Mathematics',
'B.Com- Bachelor of Commerce',
'BBA- Bachelor of Business Administration',
'B.Com (Hons.)',
'BA (Hons.) in Economics',
'Integrated Law Program- B.Com LL.B.',
'Integarted Law Program- BBA LL.B',
'BBA- Bachelor of Business Administration',
'BMS- Bachelor of Management Science',
'BFA- Bachelor of Fine Arts',
'BEM- Bachelor of Event Management',
'Integrated Law Course- BA + LL.B',
'BJMC- Bachelor of Journalism and Mass Communication',
'BFD- Bachelor of Fashion Designing',
'BSW- Bachelor of Social Work',
'BBS- Bachelor of Business Studies',
'BTTM- Bachelor of Travel and Tourism Management',
'Aviation Courses',
'B.Sc- Interior Design',
'B.Sc.- Hospitality and Hotel Administration',
'Bachelor of Design (B. Design)',
'Bachelor of Performing Arts',
'BA in History',
'CA- Chartered Accountancy',
'CS- Company Secretary',
'Bachelor in Foreign Language',
'Diploma Courses',
'Advanced Diploma Courses',
'Certificate Courses',
]
    return status;
}

export function relations():string[]{
    let relation:string[]=['Mother' ,'Father','Spouse','Son/Daughter','Self']
    return relation;
}

export function banks():string[]{
    let bank:string[]=['Andhra Pradesh Grameena Vikas Bank',
    'Andhra Pragathi Grameena Bank',
    'Arunachal Pradesh Rural Bank',
    'Aryavart Bank',
    'Assam Gramin Vikash Bank',
    'Au Small Finance Bank Limited',
    'Axis Bank Ltd.',
    'Bandhan Bank Ltd.',
    'Bangiya Gramin Vikas Bank',
    'Bank of Baroda',
    'Bank of India',
    'Bank of Maharashtra',
    'Baroda Gujarat Gramin Bank',
    'Baroda Rajasthan Kshetriya Gramin Bank',
    'Baroda UP Bank',
    'Canara Bank',
    'Capital Small Finance Bank Limited',
    'Central Bank of India',
    'Chaitanya Godavari Grameena Bank',
    'Chhattisgarh Rajya Gramin Bank',
    'City Union Bank Ltd.',
    'CSB Bank Ltd.',
    'Dakshin Bihar Gramin Bank',
    'DCB Bank Ltd.',
    'Dhanlaxmi Bank Ltd.',
    'Ellaquai Dehati Bank',
    'Equitas Small Finance Bank Limited',
    'ESAF Small Finance Bank Limited',
    'Federal Bank Ltd.',
    'Fincare Small Finance Bank Limited',
    'HDFC Bank Ltd',
    'Himachal Pradesh Gramin Bank',
    'ICICI Bank Ltd.',
    'IDBI Bank Ltd.',
    'IDFC First Bank Ltd.',
    'Indian Bank',
    'Indian Overseas Bank',
    'Induslnd Bank Ltd',
    'J&K Grameen Bank',
    'Jammu & Kashmir Bank Ltd.',
    'Jana Small Finance Bank Limited',
    'Jharkhand Rajya Gramin Bank',
    'Karnataka Bank Ltd.',
    'Karnataka Gramin Bank',
    'Karnataka Vikas Grameena Bank',
    'Karur Vysya Bank Ltd.',
    'Kerala Gramin Bank',
    'Kotak Mahindra Bank Ltd',
    'Madhya Pradesh Gramin Bank',
    'Madhyanchal Gramin Bank',
    'Maharashtra Gramin Bank',
    'Manipur Rural Bank',
    'Meghalaya Rural Bank',
    'Mizoram Rural Bank',
    'Nagaland Rural Bank',
    'Nainital Bank Ltd.',
    'North East Small Finance Bank Limited',
    'Odisha Gramya Bank',
    'Paschim Banga Gramin Bank',
    'Prathama UP Gramin Bank',
    'Puduvai Bharathiar Grama Bank',
    'Punjab & Sind Bank',
    'Punjab Gramin Bank',
    'Punjab National Bank',
    'Rajasthan Marudhara Gramin Bank',
    'RBL Bank Ltd.',
    'Saptagiri Grameena Bank',
    'Sarva Haryana Gramin Bank',
    'Saurashtra Gramin Bank',
    'Shivalik Small Finance Bank Limited',
    'South Indian Bank Ltd.',
    'State Bank of India',
    'Suryoday Small Finance Bank Limited',
    'Tamil Nadu Grama Bank',
    'Tamilnad Mercantile Bank Ltd.',
    'Telangana Grameena Bank',
    'Tripura Gramin Bank',
    'UCO Bank',
    'Ujjivan Small Finance Bank Limited',
    'Union Bank of India',
    'Unity Small Finance Bank Limited',
    'Utkal Grameen bank',
    'Utkarsh Small Finance Bank Limited',
    'Uttar Bihar Gramin Bank',
    'Uttarakhand Gramin Bank',
    'Uttarbanga Kshetriya Gramin Bank',
    'Vidharbha Konkan Gramin Bank',
    'YES Bank Ltd.',
    ]
    return bank;
}

export interface modeldata{
     id:Number;
     title:string;

}

export interface previewmodeldata{
    id:Number;
    title:string;
    filetype:string;
    filename:string;

}